### PR TITLE
Add docstrings to BMI classes

### PR DESCRIPTION
**Pull request by mdpiper**
The bulk of the changes in this pull request are the addition of [numpydoc](https://github.com/numpy/numpydoc/) docstrings to the methods of the BMI classes, following the instructions in the [guide](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt).

I also:
- moved `get_var_rank` to `get_grid_rank`
- moved `get_var_size` to `get_grid_size`
- added the `get_var_grid` method
- changed the input parameter for the `get_grid_*` methods to `grid_id`, from `long_var_name`
- updated the `BmiHeat` class and all the unit tests that use these methods

### CODE REVIEW

**Comment by mcflugen** [comment]
All of the `get_grid_*` methods now accept a grid id (as an `int`) rather than a long var name `str`.

**Comment by mcflugen** [comment]
`get_grid_rank` and `get_grid_size` should accept a grid id rather than a long var name.

**Comment by mdpiper** [comment]
One problem: changing `get_grid_rank` and `get_grid_size` will break `BmiHeat` and the unit tests until the `get_var_grid` method is implemented. (Currently, it has only an interface in `Bmi`.)

**Comment by mcflugen** [comment]
I merged the documentation into master so that we had some documentation on our [readthedocs page](http://bmi-forum.readthedocs.org). Please submit a new PR with fixes to the `get_grid_rank` and `get_grid_size` functions and their unit tests.

**Pull request merged**
